spring.application.name=SpringMCP
spring.ai.mcp.server.name=todo-management-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
server.port=8082
spring.main.banner-mode=off
logging.file.name=./logs/todo-mcp-server.log
spring.main.banner-mode=off
spring.main.web-application-type=none
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
logging.file.name=./logs/todo-mcp-server.log
spring.ai.mcp.server.name=todo-mcp-server
spring.ai.mcp.server.version=0.0.1